= A Bash script that concatenates my screen recordings into a single video
Paulo Jerônimo <paulojeronimo@gmail.com>
:idprefix:
:idseparator: -
:nofooter:
:toc: left
:ffmpeg: https://ffmpeg.org/[ffmpeg]
:SimpleScreenRecorder: https://github.com/MaartenBaert/ssr[SimpleScreenRecorder]
:project-name: terminal-video-builder
:uri-project-https: https://github.com/paulojeronimo/{project-name}
:uri-project-git: git@github.com:paulojeronimo/{project-name}
:uri-script: {uri-project-https}/blob/main/build.video.sh

== About this project

{uri-project-https}[This project] is *a straightforward video build system*,
written in Bash, that uses {ffmpeg} to create a video composed of some
other parts like other videos and an initial image displayed for some
seconds before the video.

The last update of this document was: {localdatetime}.

== What it does?

Currently, {uri-script}[this Bash script] does the following:

. It concatenates several other mkv video parts into one video
  (`v1_mkv`).
.. I usually record these video parts in my Ubuntu environment using the
software {SimpleScreenRecorder}.
The recorded videos remain in the directory
`~/Videos/simplescreen-recordings`.
. It concatenates the PNG image file (`image`) into `v1_mkv` in its
  beginning generating another video `v2_mkv`.
.. The image will be displayed by `image_screen_time` seconds before
the video `v1_mkv` starts.
. It converts the final video (`v2_mkv`) into `v2_mp4`. This is more
  suitable for publishing on some platforms like LinkedIn.

== Where it is used?

This project was created when I was working to create this post on my
LinkedIn account:

++++
<p align="center">
<iframe
src="https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7031353632339963904"
height="712" width="504" frameborder="0" allowfullscreen=""
title="Embedded post"></iframe>
</p>
++++

As I intend to develop other videos using the same process, this project
becomes helpful for this situation.

== How can I use it?

These are my steps to rebuild the video created above at any time:

[subs=attributes+]
----
$ # Changing to the directory where SimpleScreenRecorder stores the videos
$ cd ~/Videos/simplescreen-recordings
$ repo={uri-project-git}

$ # Creating a variable with the name of the directory of my video
$ video=ChatGPT-MVP

$ # Removing the current video directory if it exits
$ rm -rf $video

$ # Cloning the {project-name} project
$ git clone $repo $video && cd $video

$ # Creating links for the files that the builder will use
$ for f in ../simplescreenrecorder-2023-02-14_1*; do ln -s $f; done
$ ln -s ~/Pictures/Canva/$video.png .

$ # Building the video
$ ./build.video.sh
----

After running the process for the first time, this will be the expected
result:

----
$ ls $video.*
ChatGPT-MVP.1.mkv  ChatGPT-MVP.2.mkv  ChatGPT-MVP.2.mp4  ChatGPT-MVP.png
----

The final files to be published are named `ChatGPT-MVP.2.*`.

== Useful notes

. I usually made my screen recordings without any sound.
So, the Bash script is configured by following this rule.
If your recorded videos have sound, observe the references in the Bash
script and adapt it accordingly.
. The recorded parts of the video that compose the single one were built
  in the dimensions of 550 x 550 pixels.
Remember that the initial image added to this video must have that exact
measurement, or the build process will crash.

== Related projects

* https://paulojeronimo.com/sitemap/#ffmpeg
